# Generated by Django 4.2.19 on 2025-02-14 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_request', '0002_alter_purchaserequest_options_and_more'),
        ('vendor', '0002_alter_vendor_email_alter_vendor_fax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPPH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('nomor_spph', models.CharField(max_length=50)),
                ('tanggal_spph', models.DateField()),
                ('batas_spph', models.DateField()),
                ('perihal', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spph', to='purchase_request.purchaserequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SPPHVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('spph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spph.spph')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SPPHLampiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(null=True, upload_to='spph/lampiran/')),
                ('spph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lampiran', to='spph.spph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='spph',
            name='vendors',
            field=models.ManyToManyField(through='spph.SPPHVendor', to='vendor.vendor'),
        ),
    ]
