# Generated by Django 4.2.19 on 2025-02-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spph', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spphlampiran',
            options={'default_permissions': (), 'permissions': [('add_spph_lampiran', 'Can add SPPH lampiran'), ('change_spph_lampiran', 'Can change SPPH lampiran'), ('delete_spph_lampiran', 'Can delete SPPH lampiran'), ('view_spph_lampiran', 'Can view SPPH lampiran')]},
        ),
        migrations.AlterModelOptions(
            name='spphvendor',
            options={'default_permissions': (), 'permissions': [('add_spph_vendor', 'Can add SPPH vendor'), ('change_spph_vendor', 'Can change SPPH vendor'), ('delete_spph_vendor', 'Can delete SPPH vendor'), ('view_spph_vendor', 'Can view SPPH vendor')]},
        ),
        migrations.AlterModelTable(
            name='spphlampiran',
            table='spph_lampiran',
        ),
        migrations.AlterModelTable(
            name='spphvendor',
            table='spph_vendor',
        ),
    ]
