# Generated by Django 4.2.19 on 2025-02-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spph', '0002_alter_spphlampiran_options_alter_spphvendor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spphlampiran',
            options={'default_permissions': (), 'permissions': [('add_spph_lampiran', 'Can add SPPH lampiran'), ('delete_spph_lampiran', 'Can delete SPPH lampiran'), ('view_spph_lampiran', 'Can view SPPH lampiran')]},
        ),
        migrations.AlterModelOptions(
            name='spphvendor',
            options={'default_permissions': (), 'permissions': [('add_spph_vendor', 'Can add SPPH vendor'), ('delete_spph_vendor', 'Can delete SPPH vendor'), ('view_spph_vendor', 'Can view SPPH vendor')]},
        ),
    ]
