# Generated by Django 4.2.19 on 2025-02-14 06:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0005_alter_purchaserequestdetail_purchase_request'),
        ('spph', '0004_alter_spph_id_alter_spphlampiran_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPPHDetail',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_request.purchaserequest')),
                ('spph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spph.spph')),
            ],
            options={
                'db_table': 'spph_detail',
                'permissions': [('add_spph_detail', 'Can add SPPH detail'), ('delete_spph_detail', 'Can delete SPPH detail'), ('view_spph_detail', 'Can view SPPH detail')],
                'default_permissions': (),
            },
        ),
    ]
