# Generated by Django 4.2.19 on 2025-02-13 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrak',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_proyek', models.CharField(max_length=20)),
                ('tanggal', models.DateField()),
                ('nomor', models.CharField(max_length=100)),
                ('nama_pekerjaan', models.CharField(max_length=150)),
                ('nilai_pekerjaan', models.CharField(max_length=150)),
                ('nama_pelanggan', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('KONTRAK', 'Kontrak'), ('KONFIRMASI_ORDER', 'Konfirmasi Order')], default='KONTRAK', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
