# Generated by Django 4.2.19 on 2025-02-13 08:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kontrak', '0002_alter_kontrak_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontrakLampiran',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('nomor', models.CharField(max_length=100)),
                ('perihal', models.CharField(max_length=100, null=True)),
                ('keterangan', models.TextField(null=True)),
                ('kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lampiran', to='kontrak.kontrak')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
