# Generated by Django 4.2.19 on 2025-02-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrak', '0003_kontraklampiran'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kontraklampiran',
            table='kontrak_lampiran',
        ),
    ]
