# Generated by Django 4.2.19 on 2025-02-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrak', '0004_alter_kontraklampiran_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontraklampiran',
            options={'default_permissions': (), 'permissions': [('add_kontrak_lampiran', 'Can add kontrak lampiran'), ('change_kontrak_lampiran', 'Can change kontrak lampiran'), ('delete_kontrak_lampiran', 'Can delete kontrak lampiran'), ('view_kontrak_lampiran', 'Can view kontrak lampiran')]},
        ),
    ]
