# Generated by Django 4.2.19 on 2025-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrak', '0005_alter_kontraklampiran_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontraklampiran',
            name='lampiran',
            field=models.FileField(blank=True, null=True, upload_to='kontrak/lampiran/'),
        ),
    ]
