# Generated by Django 4.2.19 on 2025-02-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrak', '0006_kontraklampiran_lampiran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrak',
            name='nilai_pekerjaan',
            field=models.BigIntegerField(),
        ),
    ]
