# Generated by Django 4.2.19 on 2025-02-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrak', '0007_alter_kontrak_nilai_pekerjaan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontraklampiran',
            options={'default_permissions': (), 'permissions': [('add_kontrak_lampiran', 'Can add kontrak lampiran'), ('delete_kontrak_lampiran', 'Can delete kontrak lampiran'), ('view_kontrak_lampiran', 'Can view kontrak lampiran')]},
        ),
    ]
