# Generated by Django 4.2.19 on 2025-02-13 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kontrak', '0007_alter_kontrak_nilai_pekerjaan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor', models.CharField(max_length=100)),
                ('dasar', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontrak.kontrak')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestDetail',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_material', models.CharField(max_length=100)),
                ('nama_barang', models.CharField(max_length=200)),
                ('spesifikasi', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('satuan', models.CharField(max_length=10)),
                ('waktu_penyelesaian', models.DateField()),
                ('lampiran', models.FileField(blank=True, null=True, upload_to='kontrak/purchase_request/')),
                ('keterangan', models.TextField(null=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_request.purchaserequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
