# Generated by Django 4.2.19 on 2025-02-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0002_alter_purchaserequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='dasar',
        ),
    ]
