# Generated by Django 4.2.19 on 2025-02-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0003_remove_purchaserequest_dasar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestdetail',
            options={'default_permissions': (), 'permissions': [('add_purchase_request_detail', 'Can add purchase request detail'), ('delete_purchase_request_detail', 'Can delete purchase request detail'), ('view_purchase_request_detail', 'Can view purchase request detail')]},
        ),
    ]
