# Generated by Django 4.2.19 on 2025-02-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0004_alter_purchaserequestdetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestdetail',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_request.purchaserequest'),
        ),
    ]
