# Generated by Django 4.2.19 on 2025-02-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0005_alter_purchaserequestdetail_purchase_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestdetail',
            options={'default_permissions': (), 'permissions': [('add_purchase_request_detail', 'Can add purchase request detail'), ('change_purchase_request_detail', 'Can change purchase request detail'), ('delete_purchase_request_detail', 'Can delete purchase request detail'), ('view_purchase_request_detail', 'Can view purchase request detail')]},
        ),
    ]
